# Generated by Django 5.0.4 on 2024-06-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_email',
            field=models.CharField(default='test@test.test', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='author_nickname',
            field=models.CharField(default='TestNickname', max_length=24),
            preserve_default=False,
        ),
    ]
